apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: xqpsk8jn0-go 
  janus-idp.io/tekton: xqpsk8jn0-go
  backstage.io/kubernetes-id: xqpsk8jn0-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xqpsk8jn0-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  